title: "Yash Khare"
email: yashsja@gmail.com
description: >- Collection of the projects I made as a part of the MLH Fellowship(Fall 2020) Explorer Batch
baseurl: "/" 
url: "/mlh-fellowship-fall-2020" 
twitter_username: _p0lar_bear
github_username:  yashk2000

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
